const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {createTestApp}=require('./support/database');
test('owner notebook: purchases, stock, sales, damage, expenses, reports, retries and validation',async()=>{
 const {app,database}=await createTestApp();const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base=`http://127.0.0.1:${server.address().port}/api`;let token;
 async function request(path,body,method='POST',status=200,key){
  const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;
 }
 try{
  await request('/products',null,'GET',401);
  const credentials={email:'owner@example.com',password:'owner-test-password',name:'Shop Owner',setupToken:process.env.SETUP_TOKEN};
  token=(await request('/auth/setup',credentials,'POST',201)).token;
  await request('/auth/setup',credentials,'POST',409);
  await request('/auth/login',credentials);
  assert.equal((await request('/auth/check',null,'GET')).name,'Shop Owner');
  const category=await request('/categories',{name:'Beer'},'POST',201);
  assert.equal((await request('/categories',{name:' BEER '},'POST',409)).error,'Category already exists.');
  const supplier=await request('/suppliers',{name:'Supplier'},'POST',201);
  assert.equal((await request('/suppliers',{name:' supplier '},'POST',409)).error,'Supplier already exists.');
  const product=await request('/products',{name:'Cola',categoryId:category.id,unitsPerPack:24,sellingPrice:700,lowStockLevel:10},'POST',201);
  const water=await request('/products',{name:'Water',unitsPerPack:12,sellingPrice:500},'POST',201);
  assert.equal(product.current_stock,0);
  await request('/products',{name:' cola ',unitsPerPack:24,sellingPrice:700},'POST',409);
  const key=randomUUID(),purchase={supplierId:supplier.id,items:[{productId:product.id,packs:10,pricePerPack:12000},{productId:water.id,packs:2,pricePerPack:2400}]};
  const bought=await request('/purchases',purchase,'POST',201,key);
  assert.equal(Number(bought.total_amount),124800);
  assert.equal((await request('/purchases',purchase,'POST',201,key)).id,bought.id);
  await request('/purchases',{...purchase,notes:'changed'},'POST',409,key);
  let products=await request('/products',null,'GET');assert.equal(products.find(p=>p.id===product.id).current_stock,240);
  assert.equal(products.find(p=>p.id===product.id).last_purchase_price_per_item,undefined);
  assert.equal(Number((await request('/purchases/'+bought.id,null,'GET')).items.find(i=>i.product_id===product.id).price_per_item),500);
  await request('/sales',{items:[{productId:product.id,quantity:2},{productId:water.id,quantity:100}]},'POST',409);
  assert.equal((await request('/products',null,'GET')).find(p=>p.id===product.id).current_stock,240);
  const sale=await request('/sales',{paymentMethod:'mobile_money',items:[{productId:product.id,quantity:8},{productId:water.id,quantity:4}]},'POST',201,randomUUID());
  assert.equal(Number(sale.total_amount),7600);assert.equal(sale.items.length,2);
  await request('/sales',{paymentMethod:'card',items:[{productId:product.id,quantity:1}]},'POST',400);
  await request('/sales',{items:[{productId:product.id,quantity:1},{productId:product.id,quantity:1}]},'POST',400);
  const expense=await request('/expenses',{name:'Transport',amount:1000},'POST',201);
  await request('/expenses/'+expense.id,{name:'Transport',amount:500,category:'Transport'},'PUT');
  await request('/damaged-items',{productId:product.id,quantity:2,reason:'Broken'},'POST',201);
  await request('/damaged-items',{productId:water.id,quantity:100},'POST',409);
  await request('/owner-money',{type:'money_added',amount:100000},'POST',201);
  await request('/owner-money',{type:'money_taken',amount:20000},'POST',201);
  const report=await request('/reports/summary',null,'GET');
  assert.equal(Number(report.sales),7600);assert.equal(Number(report.costOfSoldItems),4800);
  assert.equal(Number(report.expenses),500);assert.equal(Number(report.damagedLosses),1000);assert.equal(Number(report.profit),1300);
  assert.equal(Number(report.cashIn),107600);assert.equal(Number(report.cashOut),145300);assert.equal(Number(report.cashDifference),-37700);
  assert.equal(report.currentStock,250);assert.equal(report.itemsPurchased,264);assert.equal(report.itemsSold,12);
  for(const period of ['weekly','monthly','yearly'])assert.equal(Number((await request('/reports/summary?period='+period,null,'GET')).profit),1300);
  await request('/reports/summary?period=custom&startDate=2026-02-30&endDate=2026-03-01',null,'GET',400);
  await request('/reports/summary?period=custom&startDate=2026-03-02&endDate=2026-03-01',null,'GET',400);
  const history=await request('/history',null,'GET');assert.equal(history.total,6);assert.ok(history.list.every(r=>!r.request_key&&!r.request_hash&&!r.journal&&!r.reversal));
  const boughtRow=history.list.find(r=>r.type==='Bought');assert.match(String(boughtRow.details),/packs/);
  assert.equal(history.list.find(r=>r.type==='Sold').details,'Mobile Money');
  assert.equal((await request('/history?type=Sold',null,'GET')).total,1);
  assert.equal((await request('/purchases/'+bought.id,null,'GET')).items.length,2);
  assert.equal((await request('/categories',null,'GET'))[0].products,1);
  await request('/products/'+product.id,{name:'Cola',unitsPerPack:24,sellingPrice:750,lowStockLevel:5},'PUT');
  assert.equal(Number((await request('/sales/'+sale.id,null,'GET')).items.find(i=>i.product_id===product.id).selling_price_per_item),700);
  await assert.rejects(database.query('DELETE FROM products WHERE id=$1',[product.id]));
  await request('/reversals',{},'POST',404);
  const preflight=await fetch(base+'/sales',{method:'OPTIONS',headers:{Origin:'http://localhost:3000','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Idempotency-Key'}});assert.match(preflight.headers.get('access-control-allow-headers'),/Idempotency-Key/i);
  const code=await request('/auth/recovery-code',{currentPassword:credentials.password});
  await request('/auth/recover',{email:credentials.email,recoveryCode:code.recoveryCode,newPassword:'new-owner-password'});
  await request('/auth/check',null,'GET',401);
 }finally{await new Promise(r=>server.close(r));await database.close();}
});
