import React from 'react';
import InventoryPage from '@/components/form/InventoryPage';
import { useInventory } from '@/core/provider/InventoryProvider';
import { Field, Payment, Table, amount, values, ShopModal, Row } from '@/components/form/AccountingFields';
export default function Sales() {
    const { receipt, setReceipt, products, settings, selected, cost, cart, product, save, productSelect, setError, setCart } = useInventory();
    return <InventoryPage title="Record sales" managerOnly={false}><section className="panel space-y-5"><h2 className="text-lg font-semibold">Sell individual items</h2><p className="text-sm text-gray-600 dark:text-gray-400">Record each sale, or a counted daily quantity per product at the actual price paid.</p><form className="space-y-5" onSubmit={e => { const b = values(e); const p = products.find(x => x.id === b.productId); if (!p)
        return; if(Number(b.quantity)<=0 || Number(b.quantity)>p.quantity){setError('Insufficient stock. Only '+p.quantity+' items are available.');return;} if (cart.some(x => x.productId === p.id)) {
        setError('Remove the existing line before changing this product quantity.');
        return;
    } setCart([...cart, { productId: p.id, name: p.name, quantity: Number(b.quantity), unitPrice: b.unitPrice, cost: p.buyingPrice }]); }}><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{productSelect}<Field label="Individual items sold" name="quantity" type="number" step="1" value="1"/><div key={selected}><Field label="Selling price per item" name="unitPrice" type="number" value={product?.selling_price}/></div></div><button type="submit" className="btn btn-outline-primary inline-flex">+ Add another item</button></form>
        <Table headers={['Product', 'Items', 'Price each', 'Line total', '']}>{cart.map((r, i) => <tr key={r.productId}><td>{r.name}</td><td>{r.quantity}</td><td>{amount(r.unitPrice)}</td><td>{amount(Number(r.unitPrice) * r.quantity)}</td><td><button className="btn btn-outline-primary inline-flex" onClick={() => setCart(cart.filter((_, j) => j !== i))}>Remove</button></td></tr>)}</Table>
        <h2 className="text-lg font-semibold">Total: {amount(cart.reduce((sum, r) => sum + Number(r.unitPrice) * r.quantity, 0))}</h2>
        <form className="space-y-5" onSubmit={e => { const b = values(e); save('sales', { ...b, items: cart.map(({ productId, quantity, unitPrice }) => ({ productId, quantity, unitPrice })), acceptBelowCost: b.acceptBelowCost === 'on' }); }}><Payment /><Field label="Notes (optional)" name="notes" optional/>{cart.some(r => Number(r.unitPrice) < Number(r.cost)) && <label className="rounded border border-warning bg-warning-light p-4 text-warning dark:bg-warning/10"><input className="form-checkbox" type="checkbox" name="acceptBelowCost" required/> This sale includes a price below stock cost. I accept this loss.</label>}<button className="btn btn-primary inline-flex disabled:opacity-50" disabled={!cart.length}>Record paid sale</button></form>
      </section><ShopModal title="Sale receipt" open={!!receipt} onClose={()=>setReceipt(null)}>{receipt&&<div className="space-y-5 bg-white p-4 text-black"><h2 className="text-center text-xl font-bold">SALE RECEIPT</h2><p>{new Date(receipt.created_at).toLocaleString('en-GB',{timeZone:'Africa/Kigali'})} · {receipt.payment_method==='bank'?'Card':receipt.payment_method.replace('_',' ')}</p><p className="break-all text-xs">Reference: {receipt.id}</p><Table headers={['Product','Category','Items sold','Price / item','Total']}>{receipt.items.map((i:Row)=><tr key={i.id}><td>{i.product_name}</td><td>{i.category_name}</td><td>{i.quantity}</td><td>{amount(i.unit_price)}</td><td>{amount(Number(i.unit_price)*i.quantity)}</td></tr>)}</Table><p className="text-right text-xl font-bold">Grand total: {amount(receipt.amount)}</p></div>}</ShopModal></InventoryPage>;
}
