import React,{useEffect,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {api} from '@/hooks/api';
import {useNotebook} from '@/core/provider/NotebookProvider';
import {Field,Table,ShopModal,Row,amount,values} from '@/components/form/AccountingFields';

const labels:Record<string,string>={products:'Products',categories:'Categories',purchases:'Purchases',sales:'Sales',expenses:'Expenses','damaged-items':'Damaged Items','owner-money':'Owner Money',history:'History',reports:'Reports',dashboard:'Dashboard'};
const actions:Record<string,string>={products:'Add Product',categories:'Add Category',purchases:'Record Purchase',sales:'Record Sale',expenses:'Add Expense','damaged-items':'Record Damaged Item','owner-money':'Record Owner Money'};
const date=(value:any)=>new Date(value).toLocaleDateString('en-GB',{timeZone:'Africa/Kigali',day:'numeric',month:'short',year:'numeric'});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kigali',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const payment=(v:string)=>({cash:'Cash',mobile_money:'Mobile Money',bank:'Bank'}[v]||v);
const entryDate=(row:Row)=>row.purchase_date||row.sale_date||row.expense_date||row.damaged_date||row.entry_date||row.date;
const stockStatus=(p:Row)=>p.current_stock===0?'Out of Stock':p.current_stock<=p.low_stock_level?'Low Stock':'In Stock';
const badgeClass:Record<string,string>={Bought:'bg-sky-100 text-sky-800',Sold:'bg-emerald-100 text-emerald-800',Expense:'bg-amber-100 text-amber-800',Damaged:'bg-rose-100 text-rose-800','Money Added':'bg-emerald-100 text-emerald-800','Money Taken':'bg-slate-200 text-slate-800'};
function Badge({children}:{children:string}){return <span className={'inline-block rounded-full px-3 py-1 text-xs font-semibold '+(badgeClass[children]||'bg-primary/10 text-primary')}>{children}</span>;}
function Empty({columns}:{columns:number}){return <tr><td colSpan={columns} className="py-10 text-center text-gray-500">No entries yet.</td></tr>;}
function History({rows,onView}:{rows:Row[];onView:(r:Row)=>void}){return <Table headers={['Date','Type','Item / Description','Quantity','Amount','Details']}>{rows.length?rows.map(r=><tr key={r.id}><td className="whitespace-nowrap">{date(r.date)}</td><td><Badge>{String(r.type)}</Badge></td><td>{r.description}</td><td>{r.quantity??'—'}</td><td className="whitespace-nowrap font-semibold">{amount(r.amount)}</td><td><div className="flex flex-wrap items-center gap-2"><span>{r.details||'—'}</span><button className="btn btn-outline-primary" onClick={()=>onView(r)}>View</button></div></td></tr>):<Empty columns={6}/>}</Table>;}
function MoneyBar({label,value,max}:{label:string;value:number;max:number}){return <div className="space-y-1"><div className="flex justify-between gap-3 text-sm"><span>{label}</span><span className="font-semibold">{amount(value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-gray-100 dark:bg-white/10"><div className={'h-full rounded-full '+(value<0?'bg-danger':'bg-primary')} style={{width:Math.min(100,max?Math.abs(value)/max*100:0)+'%'}}/></div></div>;}
export default function Notebook(){
 const location=useLocation(),resource=location.pathname.split('/')[2]||'dashboard';
 return <NotebookPage key={resource} resource={resource}/>;
}
function NotebookPage({resource}:{resource:string}){
 const {products,categories,suppliers,busy,revision,pending,save}=useNotebook();
 const [rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Row|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState('');
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Row|null>(null),[view,setView]=useState<Row|null>(null),[supplierOpen,setSupplierOpen]=useState(false);
 const [period,setPeriod]=useState('daily'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[type,setType]=useState(''),[search,setSearch]=useState('');
 const reporting=['dashboard','reports'].includes(resource);
 useEffect(()=>{
  if(['products','categories'].includes(resource))return;
  if(reporting&&period==='custom'&&(!start||!end)){setSummary(null);setLoading(false);setLoadError('');return;}
  let cancelled=false;setLoading(true);setLoadError('');setRows([]);setSummary(null);
  api.get(reporting?'/reports/summary':'/'+resource,{params:reporting?{period:resource==='dashboard'?'daily':period,startDate:start,endDate:end}:{page,type}}).then(r=>{if(cancelled)return;if(reporting)setSummary(r.data);else{setRows(r.data.list);setTotal(r.data.total);}}).catch(e=>{if(!cancelled)setLoadError(e.response?.data?.error||'Could not load this page. Please reload and try again.');}).finally(()=>{if(!cancelled)setLoading(false);});
  return()=>{cancelled=true;};
 },[resource,reporting,revision,page,period,start,end,type]);
 async function show(row:Row){
  if(resource==='products'){setView(row);return;}
  try{const r=await api.get('/'+(row.resource||resource)+'/'+row.id);setView({...r.data,resource:row.resource||resource});}catch{setLoadError('Could not load details. Please try again.');}
 }
 const productRows=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));
 return <div className="space-y-6">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">{labels[resource]}</h1><p className="mt-1 text-gray-500">{resource==='dashboard'?'How is your shop doing today?':'Your shop notebook · RWF'}</p></div>{actions[resource]&&<button className="btn btn-primary min-h-[44px]" disabled={busy||!!pending} onClick={()=>{setEditing(null);setOpen(true);}}>{actions[resource]}</button>}</header>
  {pending&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><p>One entry needs confirmation before you record another.</p><button className="btn btn-warning mt-3" disabled={busy} onClick={()=>save(pending.path,pending.body,pending.method,pending)}>{busy?'Checking...':'Confirm saved entry'}</button></section>}
  {loadError&&<p role="alert" className="rounded-lg bg-danger/10 p-4 text-danger">{loadError}</p>}
  {resource==='products'&&<section className="panel space-y-4"><label className="block max-w-sm">Find a product<input className="form-input mt-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products"/></label><Table headers={['Product','Category','In Stock','Selling Price','Low Stock At','Status','Actions']}>{productRows.length?productRows.map(p=><tr key={p.id}><td className="font-medium">{p.name}</td><td>{p.category_name||'—'}</td><td>{p.current_stock}</td><td>{amount(p.selling_price)}</td><td>{p.low_stock_level}</td><td><span className={'badge '+(p.current_stock===0?'bg-danger/10 text-danger':p.current_stock<=p.low_stock_level?'bg-warning/10 text-warning':'bg-success/10 text-success')}>{stockStatus(p)}</span></td><td><div className="flex gap-2"><button className="btn btn-outline-primary" onClick={()=>show(p)}>View</button><button className="btn btn-outline-primary" disabled={busy||!!pending} onClick={()=>{setEditing(p);setOpen(true);}}>Edit</button></div></td></tr>):<Empty columns={7}/>}</Table></section>}
  {resource==='categories'&&<section className="panel"><Table headers={['Category','Products','Actions']}>{categories.length?categories.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.products}</td><td><button className="btn btn-outline-primary" disabled={busy||!!pending} onClick={()=>{setEditing(c);setOpen(true);}}>Edit</button></td></tr>):<Empty columns={3}/>}</Table></section>}
  {resource==='purchases'&&<section className="panel flex flex-wrap items-center justify-between gap-3"><p>{suppliers.length} suppliers</p><button className="btn btn-outline-primary" disabled={busy||!!pending} onClick={()=>setSupplierOpen(true)}>Add Supplier</button></section>}
  {resource==='history'&&<label className="block max-w-xs">Show<select aria-label="Show" className="form-select mt-1" value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="">All entries</option>{['Bought','Sold','Expense','Damaged','Money Added','Money Taken'].map(t=><option key={t}>{t}</option>)}</select></label>}
  {resource==='reports'&&<section className="panel flex flex-wrap items-end gap-4"><label>Period<select aria-label="Period" className="form-select" value={period} onChange={e=>setPeriod(e.target.value)}>{Object.entries({daily:'Today',weekly:'This Week',monthly:'This Month',yearly:'This Year',custom:'Custom Date Range'}).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{period==='custom'&&<><label>From<input className="form-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Through<input className="form-input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<button className="btn btn-outline-primary print:hidden" onClick={()=>window.print()}>Print Report</button></section>}
  {loading&&<p role="status">Loading...</p>}
  {reporting&&summary&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{(resource==='dashboard'?[["Today's Sales",summary.sales,true],["Today's Purchases",summary.purchases,true],["Today's Expenses",summary.expenses,true],["Today's Profit",summary.profit,true],['Current Stock',summary.currentStock,false],['Low Stock Products',summary.lowStockProducts,false],['Damaged Items',summary.damagedItems,false]]:[['Sales',summary.sales,true],['Cost of Sold Items',summary.costOfSoldItems,true],['Expenses',summary.expenses,true],['Damaged Losses',summary.damagedLosses,true],['Profit / Loss',summary.profit,true],['Purchases',summary.purchases,true],['Items Sold',summary.itemsSold,false],['Items Purchased',summary.itemsPurchased,false],['Low Stock Products',summary.lowStockProducts,false]]).map(([label,value,currency])=><article className="panel space-y-2" key={String(label)}><p className="text-gray-500">{label}</p><p className={'text-2xl font-semibold '+(Number(value)<0?'text-danger':'')}>{currency?amount(value):Number(value).toLocaleString()}</p></article>)}</div><div className="grid gap-4 sm:grid-cols-3">{[['Cash In',summary.cashIn],['Cash Out',summary.cashOut],['Cash Difference',summary.cashDifference]].map(([label,value])=><article className="panel space-y-2" key={String(label)}><p className="text-gray-500">{label}</p><p className={'text-2xl font-semibold '+(Number(value)<0?'text-danger':'')}>{amount(value)}</p></article>)}</div>{resource==='reports'&&<section className="panel space-y-4"><h2 className="text-lg font-semibold">How profit was made</h2>{[[ 'Sales',Number(summary.sales)],['What sold items cost',Number(summary.costOfSoldItems)],['Expenses',Number(summary.expenses)],['Damaged items',Number(summary.damagedLosses)],['Profit / Loss',Number(summary.profit)]].map(([label,value])=><MoneyBar key={String(label)} label={String(label)} value={Number(value)} max={Math.max(Number(summary.sales),Number(summary.purchases),Number(summary.costOfSoldItems),Math.abs(Number(summary.profit)),1)}/>)}</section>}<p className="text-sm text-gray-500">{resource==='dashboard'?'Figures are for today in Kigali time. Stock is what you have now. Profit is not the same as cash: buying stock spends money, but profit counts only items already sold.':'Profit is sales minus the cost of items sold, expenses, and damaged items. Purchases stay in stock until they are sold. Dates use Kigali time.'}</p>{resource==='dashboard'&&!!(summary.lowStockItems||[]).length&&<section className="panel space-y-3"><h2 className="text-lg font-semibold">Need to restock</h2><ul className="space-y-2">{summary.lowStockItems.map((p:Row)=><li key={p.name} className="flex justify-between gap-4 text-base"><span>{p.name}</span><span className="font-semibold">{p.current_stock} left</span></li>)}</ul></section>}<section className="panel space-y-4"><h2 className="text-lg font-semibold">Recent Activity</h2><History rows={summary.activity||[]} onView={show}/></section></>}
  {reporting&&period==='custom'&&(!start||!end)&&<p>Choose a start and end date.</p>}
  {!reporting&&!['products','categories'].includes(resource)&&!loading&&!loadError&&<section className="panel">{resource==='history'?<History rows={rows} onView={show}/>:<EntryTable resource={resource} rows={rows} onView={show} onEdit={r=>{setEditing(r);setOpen(true);}} disabled={busy||!!pending}/>}<div className="mt-5 flex items-center justify-between gap-3"><button className="btn btn-outline-primary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} · {total} entries</span><button className="btn btn-outline-primary" disabled={page*50>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>}
  <ShopModal title={editing?'Edit '+({products:'Product',categories:'Category',expenses:'Expense'}[resource]||'Entry'):actions[resource]||'Entry'} open={open} onClose={()=>{if(!busy)setOpen(false);}}>{open&&<EntryForm resource={resource} editing={editing} onSaved={()=>setOpen(false)}/>}</ShopModal>
  <ShopModal title="Add Supplier" open={supplierOpen} onClose={()=>{if(!busy)setSupplierOpen(false);}}>{supplierOpen&&<EntryForm resource="suppliers" editing={null} onSaved={()=>setSupplierOpen(false)}/>}</ShopModal>
  <ShopModal title={resource==='products'?'Product Details':'Entry Details'} open={!!view} onClose={()=>setView(null)}>{view&&<Details row={view}/>}</ShopModal>
 </div>;
}
function EntryTable({resource,rows,onView,onEdit,disabled}:{resource:string;rows:Row[];onView:(r:Row)=>void;onEdit:(r:Row)=>void;disabled:boolean}){
 const headers:Record<string,string[]>={purchases:['Date','Supplier','Products','Items Received','Total Paid','Actions'],sales:['Date','Items Sold','Payment','Total','Actions'],expenses:['Date','Expense','Category','Amount','Details','Actions'],'damaged-items':['Date','Product','Quantity','Reason','Loss'],'owner-money':['Date','Type','Amount','Notes']};
 return <Table headers={headers[resource]||[]}>{rows.length?rows.map(r=><tr key={r.id}><td className="whitespace-nowrap">{date(entryDate(r))}</td>{resource==='purchases'?<><td>{r.supplier_name||'—'}</td><td>{r.products}</td><td>{r.quantity}</td><td>{amount(r.total_amount)}</td></>:resource==='sales'?<><td>{r.quantity}</td><td>{payment(r.payment_method)}</td><td>{amount(r.total_amount)}</td></>:resource==='expenses'?<><td>{r.name}</td><td>{r.category||'—'}</td><td>{amount(r.amount)}</td><td>{r.description||'—'}</td></>:resource==='damaged-items'?<><td>{r.product_name}</td><td>{r.quantity}</td><td>{r.reason||'—'}</td><td>{amount(r.total_loss)}</td></>:<><td><Badge>{r.type==='money_added'?'Money Added':'Money Taken'}</Badge></td><td>{amount(r.amount)}</td><td>{r.notes||'—'}</td></>}{['purchases','sales','expenses'].includes(resource)&&<td><div className="flex gap-2"><button className="btn btn-outline-primary" onClick={()=>onView(r)}>View</button>{resource==='expenses'&&<button className="btn btn-outline-primary" disabled={disabled} onClick={()=>onEdit(r)}>Edit</button>}</div></td>}</tr>):<Empty columns={headers[resource]?.length||1}/>}</Table>;
}
function EntryForm({resource,editing,onSaved}:{resource:string;editing:Row|null;onSaved:()=>void}){
 const {products,categories,suppliers,save,busy,pending}=useNotebook();
 const [lines,setLines]=useState<Row[]>([{productId:'',packs:'1',quantity:'1',pricePerPack:'',unitsPerPack:1}]);
 const update=(index:number,key:string,value:string)=>setLines(old=>old.map((line,i)=>{if(i!==index)return line;if(key==='productId'){const p=products.find(p=>p.id===value);return {...line,productId:value,unitsPerPack:p?.units_per_pack||1,sellingPrice:p?.selling_price||0};}return {...line,[key]:value};}));
 const purchase=resource==='purchases', multi=purchase||resource==='sales';
 const total=lines.reduce((sum,l)=>sum+(purchase?Number(l.packs)*Number(l.pricePerPack):Number(l.quantity)*Number(l.sellingPrice||0)),0);
 return <form className="space-y-5" onSubmit={async e=>{const body:Row=values(e);if(multi)body.items=lines;if(await save(resource+(editing?'/'+editing.id:''),body,editing?'put':'post'))onSaved();}}><fieldset disabled={busy||!!pending} className="space-y-5 disabled:opacity-60">
  {['products','categories','suppliers'].includes(resource)&&<Field label={resource==='products'?'Product name':resource==='categories'?'Category name':'Supplier name'} name="name" value={editing?.name}/>}
  {resource==='products'&&<><label className="block">Category<select aria-label="Category" name="categoryId" className="form-select min-h-[44px]" defaultValue={editing?.category_id||''}><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Items per pack" name="unitsPerPack" type="number" step="1" value={editing?.units_per_pack||12}/><Field label="Selling price per item (RWF)" name="sellingPrice" type="number" value={editing?.selling_price} step="0.01"/><Field label="Low stock at" name="lowStockLevel" type="number" step="1" value={editing?.low_stock_level??0}/></div>{!editing&&<p className="text-sm text-gray-500">After adding this product, record a purchase to add stock.</p>}</>}
  {['products','categories'].includes(resource)&&<Field label="Description (optional)" name="description" optional value={editing?.description}/>}
  {resource==='suppliers'&&<><Field label="Phone (optional)" name="phone" optional/><Field label="Email (optional)" name="email" type="email" optional/><Field label="Address (optional)" name="address" optional/><Field label="Notes (optional)" name="notes" optional/></>}
  {!['products','categories','suppliers'].includes(resource)&&<Field label="Date" name="date" type="date" value={editing?new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kigali'}).format(new Date(entryDate(editing))):today()}/>}
  {purchase&&<label className="block">Supplier (optional)<select aria-label="Supplier (optional)" className="form-select" name="supplierId"><option value="">No supplier</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}
  {multi&&<div className="space-y-4">{lines.map((line,i)=><section className="rounded-xl border border-gray-200 p-4 space-y-3 dark:border-gray-700" key={i}><div className="flex items-center justify-between"><h3 className="font-semibold">Product {i+1}</h3>{lines.length>1&&<button className="text-danger underline p-2" type="button" onClick={()=>setLines(old=>old.filter((_,n)=>n!==i))}>Remove</button>}</div><label className="block">Product<select aria-label="Product" className="form-select" required value={line.productId} onChange={e=>update(i,'productId',e.target.value)}><option value="">Choose a product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{purchase?'':` (${p.current_stock} available)`}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2">{purchase?<><label>Packs<input className="form-input" required type="number" min="1" step="1" value={line.packs} onChange={e=>update(i,'packs',e.target.value)}/></label><label>Items per pack<input className="form-input" required type="number" min="1" step="1" value={line.unitsPerPack} onChange={e=>update(i,'unitsPerPack',e.target.value)}/></label><label>Price per pack (RWF)<input className="form-input" required type="number" min="0" step="0.01" value={line.pricePerPack} onChange={e=>update(i,'pricePerPack',e.target.value)}/></label></>:<><label>Individual items sold<input className="form-input" required type="number" min="1" step="1" max={products.find(p=>p.id===line.productId)?.current_stock||undefined} value={line.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></label><label>Price per item (RWF)<input className="form-input" required type="number" min="0" step="0.01" value={line.sellingPrice??''} onChange={e=>update(i,'sellingPrice',e.target.value)}/></label></>}</div><p className="text-sm">{purchase?`${Number(line.packs)*Number(line.unitsPerPack)} items received · `:''}{amount(purchase?Number(line.packs)*Number(line.pricePerPack):Number(line.quantity)*Number(line.sellingPrice||0))}</p></section>)}<button type="button" className="btn btn-outline-primary" disabled={lines.length>=100} onClick={()=>setLines(old=>[...old,{productId:'',packs:'1',quantity:'1',unitsPerPack:1,pricePerPack:''}])}>Add another product</button><p className="text-xl font-semibold">Total: {amount(total)}</p></div>}
  {resource==='sales'&&<label className="block">Payment<select aria-label="Payment" className="form-select" name="paymentMethod"><option value="cash">Cash</option><option value="mobile_money">Mobile Money</option><option value="bank">Bank</option></select></label>}
  {resource==='expenses'&&<><Field label="Expense name" name="name" value={editing?.name}/><label className="block">Category (optional)<input className="form-input" name="category" list="expense-categories" defaultValue={editing?.category}/><datalist id="expense-categories">{['Transport','Electricity','Rent','Food','Cleaning','Phone','Other'].map(c=><option key={c} value={c}/>)}</datalist></label><Field label="Amount (RWF)" name="amount" type="number" step="0.01" value={editing?.amount}/><Field label="Details (optional)" name="description" optional value={editing?.description}/></>}
  {resource==='damaged-items'&&<><label className="block">Product<select aria-label="Product" className="form-select" required name="productId"><option value="">Choose a product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({p.current_stock} available)</option>)}</select></label><Field label="Quantity" name="quantity" type="number" step="1"/><Field label="Reason (optional)" name="reason" optional/></>}
  {resource==='owner-money'&&<><label className="block">Type<select aria-label="Type" className="form-select" name="type"><option value="money_added">Money Added to Business</option><option value="money_taken">Money Taken from Business</option></select></label><Field label="Amount (RWF)" name="amount" type="number" step="0.01"/></>}
  {['purchases','sales','owner-money'].includes(resource)&&<Field label="Notes (optional)" name="notes" optional/>}
  <button className="btn btn-primary min-h-[44px]" type="submit">{busy?'Saving...':'Save '+({products:'product',categories:'category',suppliers:'supplier',purchases:'purchase',sales:'sale',expenses:'expense','damaged-items':'damaged items','owner-money':'owner money'}[resource]||'entry')}</button>
 </fieldset></form>;
}
function Details({row}:{row:Row}){
 if(row.current_stock!==undefined)return <dl className="grid grid-cols-2 gap-4">{Object.entries({Product:row.name,Category:row.category_name||'—','In Stock':row.current_stock,'Selling Price':amount(row.selling_price),'Items per Pack':row.units_per_pack,'Low Stock At':row.low_stock_level,Status:stockStatus(row),Description:row.description||'—'}).map(([key,value])=><React.Fragment key={key}><dt className="text-gray-500">{key}</dt><dd>{value}</dd></React.Fragment>)}</dl>;
 const purchase=row.resource==='purchases';
 return <div className="space-y-4"><p>{date(entryDate(row))}</p>{row.payment_method&&<p>Payment: {payment(row.payment_method)}</p>}{row.items?<><Table headers={purchase?['Product','Packs','Items','Price per Pack','Total']:['Product','Quantity','Price per Item','Total']}>{row.items.map((i:Row)=><tr key={i.id}><td>{i.product_name}</td>{purchase?<><td>{i.packs}</td><td>{i.total_items}</td><td>{amount(i.price_per_pack)}</td><td>{amount(i.total_cost)}</td></>:<><td>{i.quantity}</td><td>{amount(i.selling_price_per_item)}</td><td>{amount(i.line_total)}</td></>}</tr>)}</Table><p className="text-xl font-semibold">Grand total: {amount(row.total_amount)}</p></>:<><p className="font-semibold">{row.name||row.product_name||(row.type==='money_added'?'Money Added':row.type==='money_taken'?'Money Taken':'')}</p>{row.quantity&&<p>Quantity: {row.quantity}</p>}<p className="text-xl font-semibold">{amount(row.amount??row.total_loss)}</p></>}{(row.notes||row.description||row.reason)&&<p>{row.notes||row.description||row.reason}</p>}</div>;
}

