import React from 'react';
import InventoryPage from '@/components/form/InventoryPage';
import { useInventory } from '@/core/provider/InventoryProvider';
import { Table, amount, Row } from '@/components/form/AccountingFields';
export default function Reports() {
    const { tab, reportDate, setReportDate, settings, summary, period, startDate, endDate, setPeriod, setStartDate, setEndDate } = useInventory();
    return <InventoryPage title={tab==='dashboard'?'Dashboard':'Reports'} managerOnly={true}><>
        {tab!=='dashboard'&&<section className="panel flex flex-wrap items-end gap-4 print:hidden"><label className="block space-y-2 text-sm font-medium">Period<select className="form-select" value={period} onChange={e => setPeriod(e.target.value)}>{['daily', 'weekly', 'monthly', 'yearly', 'custom'].map(p => <option key={p}>{p}</option>)}</select></label>{period === 'custom' && <><label className="block space-y-2 text-sm font-medium">From<input className="form-input" type="date" value={startDate} onChange={e => setStartDate(e.target.value)}/></label><label className="block space-y-2 text-sm font-medium">Through<input className="form-input" type="date" value={endDate} onChange={e => setEndDate(e.target.value)}/></label></>}<button className="btn btn-primary inline-flex disabled:opacity-50" onClick={() => window.print()} type="button">Print / Save PDF</button>{period!=='custom'&&<label>Selected date<input className="form-input" type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label>}</section>}
        {summary ? <><p className="text-sm text-gray-600 dark:text-gray-400">Report time zone: {summary.timezone}. Week starts Monday. All amounts in RWF.</p><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[['Revenue', summary.revenue], ['Cost of items sold', summary.costOfGoodsSold], ['Gross profit', summary.grossProfit], ['Expenses', summary.expenses], ['Stock losses / count shortages', summary.stockLosses], ['Stock count gains', summary.stockGains], ['Profit / loss', summary.netProfit]].map(([label, value]) => <article key={label} className={'panel space-y-2 ' + (Number(value) < 0 ? 'text-danger' : '')}><span className="block text-sm text-gray-500 dark:text-gray-400">{label}</span><strong className="block text-2xl font-semibold">{amount(value)}</strong></article>)}</div>
          <section className="panel space-y-4"><h2 className="text-lg font-semibold">Business overview</h2><div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{[['Sales',summary.salesCount],['Items sold',summary.totalQuantitySold],['Products',summary.totalProducts],['Stock remaining',summary.currentStock],['Low-stock products',summary.lowStockProducts],['Damaged items',summary.damagedQuantity]].map(([label,value])=><p key={label}>{label}: <strong>{value}</strong></p>)}</div><h3>Sales by payment method</h3><Table headers={['Payment method','Revenue']}>{summary.paymentBreakdown.map((r:Row)=><tr key={r.payment_method}><td>{r.payment_method==='bank'?'Card':r.payment_method.replace('_',' ')}</td><td>{amount(r.amount)}</td></tr>)}</Table><h3>Expense breakdown</h3><Table headers={['Category','Amount']}>{summary.expenseBreakdown.map((r:Row)=><tr key={r.category}><td>{r.category}</td><td>{amount(r.amount)}</td></tr>)}</Table></section><section className="panel space-y-5"><h2 className="text-lg font-semibold">Money movement</h2><Table headers={['Account', 'Opening', 'Money in', 'Money out', 'Closing']}>{summary.cash.map((r: Row) => <tr key={r.account}><td>{r.account.replace('_', ' ')}</td><td>{amount(r.opening)}</td><td>{amount(r.received)}</td><td>{amount(r.paid)}</td><td>{amount(r.closing)}</td></tr>)}</Table><p className="text-sm text-gray-600 dark:text-gray-400">Closing balances assume all opening funds, receipts and payments have been recorded. Compare cash with the actual till.</p></section>
          <section className="panel space-y-5"><h2 className="text-lg font-semibold">Items sold</h2><Table headers={['Product', 'Net items sold', 'Revenue']}>{summary.bestSelling.map((r: Row) => <tr key={r.product_id}><td>{r.name}</td><td>{r.quantity}</td><td>{amount(r.revenue)}</td></tr>)}</Table></section>
          <section className="panel space-y-5"><h2 className="text-lg font-semibold">Remaining stock · {amount(summary.inventoryValue)} at cost</h2><Table headers={['Product', 'Items remaining', 'Value at cost']}>{summary.inventory.map((r: Row) => <tr key={r.id}><td>{r.name}</td><td>{r.quantity}{r.quantity <= r.low_stock_level && ' · Low stock'}</td><td>{amount(r.value)}</td></tr>)}</Table></section>
          <section className="panel space-y-5"><h2 className="text-lg font-semibold">Period activity</h2><Table headers={['Time', 'Type', 'Details', 'Amount']}>{summary.activity.map((r: Row) => <tr key={r.id}><td>{new Date(r.created_at).toLocaleString(undefined, { timeZone: settings.timezone })}</td><td>{r.kind}{r.reversed_by && ' (reversed)'}</td><td>{r.category} {r.notes} {r.items.map((i: Row) => `${i.product_name} × ${i.quantity}`).join(', ')}</td><td>{amount(r.amount)}</td></tr>)}</Table></section>
        </> : <p className="text-sm text-gray-600 dark:text-gray-400">{period === 'custom' && (!startDate || !endDate) ? 'Choose a start and end date.' : 'Loading report…'}</p>}
      </></InventoryPage>;
}
